name: Build all & release
permissions:
  contents: write
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false

jobs:
  build:
    name: Build all
    strategy:
      matrix:
        target:
          - device: xiaomi-beryllium-ebbg
            repo: https://git.codelinaro.org/clo/qcomlt/u-boot.git
            ref: 6fc40f2499b1a517487933d7d81a482f6dce7751
            config: "qcom_defconfig phone.config"
            device_tree: "qcom/sdm845-xiaomi-beryllium-ebbg"
          - device: xiaomi-beryllium-tianma
            repo: https://git.codelinaro.org/clo/qcomlt/u-boot.git
            ref: 6fc40f2499b1a517487933d7d81a482f6dce7751
            config: "qcom_defconfig phone.config"
            device_tree: "qcom/sdm845-xiaomi-beryllium-tianma"
          - device: fairphone-fp5
            repo: https://gitlab.postmarketos.org/tauchgang/u-boot.git
            ref: 0031cc83a4455d8aa4786788fde25d1690ba6701
            config: "qcm6490_defconfig qcom-phone.config"
            device_tree: "qcom/qcm6490-fairphone-fp5"
            header_version: "2"
    uses: ./.github/workflows/build.yml
    with:
      device: ${{ matrix.target.device }}
      repo: ${{ matrix.target.repo }}
      ref: ${{ matrix.target.ref }}
      config: ${{ matrix.target.config }}
      device_tree: ${{ matrix.target.device_tree }}
      header_version: ${{ matrix.target.header_version }}

  release:
    if: github.event_name == 'workflow_dispatch' && inputs.tag != ''
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: u-boot-*
          path: output/
          merge-multiple: true
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ inputs.tag }}
          files: |
            output/*
